### PR TITLE
WIP: migrate to mathjs@4.0.0 

### LINKED ISSUE #96: migrate to Mathjs@4.0.0
mathjs@4.0.0 came up with breaking updates - it doesn't support simplified comparison of string:
```
"abc" == "abc"
```
but we can fix it but little fix: https://github.com/josdejong/mathjs/issues/1051

### PR DESCRIPTION
**Pull request by poush**
Fixes #96 

@hyzhak Please review, there could be some mistakes. Please provide your suggestions.

### CODE REVIEW

**Comment by poush** [comment]
There is one more way, I think we can create our own module for math.js which basically import math.js, applies the fix and then export it again. Thus we do not have to replicate it everywhere it is required.

**Comment by hyzhak** [comment]
@poush 👍  I'll pull it and try locally

**Comment by hyzhak** [comment]
hi @poush! Think we add test here. 

I have a similar extension to Math.js:

https://github.com/internetarchive/internet-archive-google-action/blob/master/functions/src/mathjs/includes.js

which is tested here:

https://github.com/internetarchive/internet-archive-google-action/blob/master/functions/tests/mathjs/patches.spec.js

please add similar tests for your case and add this mathjs extension to `https://github.com/internetarchive/internet-archive-google-action/blob/master/functions/src/mathjs/` directory as I have done for `include.js`.

**Comment by poush** [comment]
@hyzhak Updated! Please see.

**Comment by hyzhak** [comment]
@poush thanks! could you fix the style?

**Pull request closed without merging**
